---
apiVersion: v1
kind: Service
metadata:
  name: stable
  namespace: gloo-rollouts-demo
  labels:
    app: gloo-rollouts-demo
    service: gloo-rollouts-demo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: gloo-rollouts-demo
