apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: canary
  namespace: gloo-rollouts-demo
spec:
  hosts:
    - example.com
  ports:
    - number: 8080
      protocol: HTTP
      targetPort:
        number: 8080
  services:
    - name: canary
      namespace: gloo-rollouts-demo
---
apiVersion: v1
kind: Service
metadata:
  name: canary
  namespace: gloo-rollouts-demo
  labels:
    app: gloo-rollouts-demo
    service: gloo-rollouts-demo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: gloo-rollouts-demo